# Exercícios 1, 2 e 3 da Lista 3

In [1]:
import numpy as np
import pandas as pd

## Exercício 1)

In [2]:
x = np.array([[0,0,0]])
print(x)

A = np.array([[10,  3,  1],
              [ 2,-10,  3],
              [ 1,  3, 10]])
print(A)

B = np.array([[14],
              [-5],
              [14]])
print(B)

[[0 0 0]]
[[ 10   3   1]
 [  2 -10   3]
 [  1   3  10]]
[[14]
 [-5]
 [14]]


In [7]:
# x = (A^(-1))*B
x = np.matmul(np.linalg.inv(A), B)
print(x)

[[1.]
 [1.]
 [1.]]


### Jacobi

In [11]:
x = np.array([[0,0,0]])
print(x)

A = np.array([[10,  3,  1],
              [ 2,-10,  3],
              [ 1,  3, 10]])
print(A)

B = np.array([[14],
              [-5],
              [14]])
print(B)

[[0 0 0]]
[[ 10   3   1]
 [  2 -10   3]
 [  1   3  10]]
[[14]
 [-5]
 [14]]


In [12]:
convergencia = False
it = 0
a = [0]
convergiu = ["Não"]
while convergencia == False:
    
    xn = np.zeros(len(x[0]), dtype=float)
    erro = np.zeros(len(x[0]), dtype=float)
    
    for i in range(len(x[0])):
    
        soma = 0
    
        for j in range(len(x[0])):
                
            if j != i:

                soma += A[i,j]*x[it,j]
    
        xn[i] = (1 / A[i,i]) * (B[i] - soma)
    
            
    x = np.vstack([x,xn]) 
    it += 1    
    
    
    
    for i in range(len(x[0])):
    
        erro[i] = np.absolute(x[it,i] - x[it-1,i])
        
    a.append(np.max(erro))
    
    # print(f'{it}:  {x[it,0]}  {x[it,1]}  {x[it,2]} : {a[it]}')
    
    if a[it] < 0.0001:
        convergencia = True
        convergiu.append("Sim")
    else:
        convergiu.append("Não")

In [13]:
i = [i for i in range(it+1)]
print(i)

Jacobi_DF = pd.DataFrame(x, columns = ["X1(m)", "X2(m)", "X3(m)"], index = i)

Jacobi_DF["Max"] = a
Jacobi_DF["Convergiu"] = convergiu

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [14]:
Jacobi_DF

X1(m)     X2(m)     X3(m)       Max Convergiu
0   0.000000  0.000000  0.000000  0.000000       Não
1   1.400000  0.500000  1.400000  1.400000       Não
2   1.110000  1.200000  1.110000  0.700000       Não
3   0.929000  1.055000  0.929000  0.181000       Não
4   0.990600  0.964500  0.990600  0.090500       Não
5   1.011590  0.995300  1.011590  0.030800       Não
6   1.000251  1.005795  1.000251  0.011339       Não
7   0.998236  1.000126  0.998236  0.005669       Não
8   1.000139  0.999118  1.000139  0.001902       Não
9   1.000251  1.000069  1.000251  0.000951       Não
10  0.999954  1.000125  0.999954  0.000297       Não
11  0.999967  0.999977  0.999967  0.000148       Não
12  1.000010  0.999983  1.000010  0.000043       Sim

### Gauss-Seidel

In [15]:
x = np.array([[0,0,0]])
print(x)

A = np.array([[10,  3,  1],
              [ 2,-10,  3],
              [ 1,  3, 10]])
print(A)

B = np.array([[14],
              [-5],
              [14]])
print(B)

[[0 0 0]]
[[ 10   3   1]
 [  2 -10   3]
 [  1   3  10]]
[[14]
 [-5]
 [14]]


In [16]:
convergencia = False
it = 0
a = [0]
convergiu = ["Não"]
while convergencia == False:
    
    xn = np.zeros(len(x[0]), dtype=float)
    erro = np.zeros(len(x[0]), dtype=float)
    
    for i in range(len(x[0])):
    
        soma = 0
        soma_f = 0
        
    
        for j in range(i):
            
            soma_f += A[i,j]*xn[j]
    
        for j in range(i+1, len(x[0])):
            
            if j != i:

                soma += A[i,j]*x[it,j]
    
        xn[i] = (1 / A[i,i]) * (B[i] - soma - soma_f)
    
            
    x = np.vstack([x,xn]) 
    it += 1    
    
    for i in range(len(x[0])):
    
        erro[i] = np.absolute(x[it,i] - x[it-1,i])
        
    a.append(np.max(erro))
    
    # print(f'{it}:  {x[it,0]}  {x[it,1]}  {x[it,2]} : {a[it]}')
    
    if a[it] < 0.0001:
        convergencia = True
        convergiu.append("Sim")
    else:
        convergiu.append("Não")

In [17]:
i = [i for i in range(it+1)]
print(i)

Gauss_Seidel_DF = pd.DataFrame(x, columns = ["X1(m)", "X2(m)", "X3(m)"], index = i)

Gauss_Seidel_DF["Max"] = a
Gauss_Seidel_DF["Convergiu"] = convergiu

[0, 1, 2, 3, 4, 5, 6, 7]


In [18]:
Gauss_Seidel_DF

X1(m)     X2(m)     X3(m)       Max Convergiu
0  0.000000  0.000000  0.000000  0.000000       Não
1  1.400000  0.780000  1.026000  1.400000       Não
2  1.063400  1.020480  0.987516  0.336600       Não
3  0.995104  0.995276  1.001907  0.068296       Não
4  1.001227  1.000817  0.999632  0.006122       Não
5  0.999792  0.999848  1.000066  0.001435       Não
6  1.000039  1.000028  0.999988  0.000247       Não
7  0.999993  0.999995  1.000002  0.000046       Sim

## Exercício 2)

1) Ler dados da rede e formar matriz **Y** <br><br>
2) Inicializar contador de iterações *i=0*. Arbitrar valores iniciais das tensões *E* para as barras PQ; arbitrar valores iniciais de tetha para as barras PV.<br><br>
3) Para *k = 1, ...,n*, calcular tensão E<sub>k</sub><sup>i+1</sup>, exceto para a barra slack; e para a barra PV calcular apenas o theta <br><br>
4) Calcular os valores de P<sub>k</sub><sup>esp</sup> para as barras PQ e PV<br><br>
5) Calcular os valores de Q<sub>k</sub><sup>esp</sup> para as barras PQ

6) Realizar os cálculos: <br>

&nbsp;&nbsp;&nbsp;dP<sub>k</sub> = |P<sub>k</sub><sup>calc</sup> - P<sub>k</sub><sup>esp</sup>| para as barras PQ e PV <br>
&nbsp;&nbsp;&nbsp;dQ<sub>k</sub> = |Q<sub>k</sub><sup>calc</sup> - Q<sub>k</sub><sup>esp</sup>| para as barras PQ <br>

7) Obter o valor maximo de mismatches entre todos os valores de *dP<sub>k</sub>* e *dQ<sub>k</sub>*, se ele for menor que uma tolerânicia, o algoritmo se encerra e o estado da rede foi determinado. Caso contrário, deve-se incrementar contador de iterações *i = i + 1* e retornar para passo 3) <br><br>

## Exercício 3)

### a) S2 = 0.3 + 0.3j

In [19]:
Z1 = 0.1 + 0.3j
Z2 = 0.2 + 0.6j

E1 = 1

E2 = [1]
Y = np.zeros((2,2), dtype=np.complex128)

S2 = 0.3 + 0.3j

Zeq = (Z1 * Z2) / (Z1 + Z2)

y12 = 1/Zeq
print(y12)

Y[0,0] = y12
Y[0,1] = -y12
Y[1,0] = -y12
Y[1,1] = y12

(1.4999999999999998-4.5j)


In [20]:
convergencia = False
i = 0
tolerancia = 0.0001

S2_final = np.conj(Y[1,0]*E1 + Y[1,1]*E2[i]) * E2[i]

print(f'{i} |  V2 = {np.absolute(E2[i]):.5f}  |  O = {np.angle(E2[i],deg=True):.5f}°  |  P2 = {np.real(S2_final):.5f}  |  Q2 = {np.imag(S2_final):.5f}')

while convergencia == False:
    

    E2_new = (1/Y[1,1]) * (np.conj(S2)/np.conj(E2[i]) - Y[1,0]*E1)
    # print(E2_new)
    
    E2.append(E2_new)
    
    i += 1
    
    S2_final = np.conj(Y[1,0]*E1 + Y[1,1]*E2[i]) * E2[i]
    
    print(f'{i} |  V2 = {np.absolute(E2[i]):.5f}  |  O = {np.angle(E2[i],deg=True):.5f}°  |  P2 = {np.real(S2_final):.5f}  |  Q2 = {np.imag(S2_final):.5f}')
    
    if tolerancia > np.absolute(E2[i] - E2[i-1]):
        convergencia = True
        

0 |  V2 = 1.00000  |  O = 0.00000°  |  P2 = 0.00000  |  Q2 = 0.00000
1 |  V2 = 1.08074  |  O = 2.12110°  |  P2 = 0.31200  |  Q2 = 0.33600
2 |  V2 = 1.07334  |  O = 2.12110°  |  P2 = 0.29795  |  Q2 = 0.29795
3 |  V2 = 1.07385  |  O = 2.13472°  |  P2 = 0.30007  |  Q2 = 0.30021
4 |  V2 = 1.07380  |  O = 2.13472°  |  P2 = 0.29999  |  Q2 = 0.29999


### a) S2 = 0.8 + 0.8j

In [21]:
S2 = 0.8 + 0.8j
E2 = [1]

In [22]:
convergencia = False
i = 0
tolerancia = 0.0001

S2_final = np.conj(Y[1,0]*E1 + Y[1,1]*E2[i]) * E2[i]

print(f'{i} |  V2 = {np.absolute(E2[i]):.5f}  |  O = {np.angle(E2[i],deg=True):.5f}°  |  P2 = {np.real(S2_final):.5f}  |  Q2 = {np.imag(S2_final):.5f}')

while convergencia == False:
    

    E2_new = (1/Y[1,1]) * (np.conj(S2)/np.conj(E2[i]) - Y[1,0]*E1)
    # print(E2_new)
    
    E2.append(E2_new)
    
    i += 1
    
    S2_final = np.conj(Y[1,0]*E1 + Y[1,1]*E2[i]) * E2[i]
    
    print(f'{i} |  V2 = {np.absolute(E2[i]):.5f}  |  O = {np.angle(E2[i],deg=True):.5f}°  |  P2 = {np.real(S2_final):.5f}  |  Q2 = {np.imag(S2_final):.5f}')
    
    if tolerancia > np.absolute(E2[i] - E2[i-1]):
        convergencia = True

0 |  V2 = 1.00000  |  O = 0.00000°  |  P2 = 0.00000  |  Q2 = 0.00000
1 |  V2 = 1.21801  |  O = 5.02408°  |  P2 = 0.88533  |  Q2 = 1.05600
2 |  V2 = 1.17131  |  O = 5.02408°  |  P2 = 0.76932  |  Q2 = 0.76932
3 |  V2 = 1.17830  |  O = 5.19388°  |  P2 = 0.80239  |  Q2 = 0.80716
4 |  V2 = 1.17695  |  O = 5.19388°  |  P2 = 0.79908  |  Q2 = 0.79908
5 |  V2 = 1.17715  |  O = 5.19893°  |  P2 = 0.80007  |  Q2 = 0.80021
6 |  V2 = 1.17711  |  O = 5.19893°  |  P2 = 0.79997  |  Q2 = 0.79997


### b) 10h - Perda da linha 1

In [23]:
# Z1 = 0.1 + 0.3j
Z2 = 0.2 + 0.6j

E1 = 1

E2 = [1]
Y = np.zeros((2,2), dtype=np.complex128)

S2 = 0.5 + 0.5j

Zeq = Z2

y12 = 1/Zeq
print(y12)

Y[0,0] = y12
Y[0,1] = -y12
Y[1,0] = -y12
Y[1,1] = y12

(0.5000000000000001-1.5j)


In [24]:
convergencia = False
i = 0
tolerancia = 0.0001

S2_final = np.conj(Y[1,0]*E1 + Y[1,1]*E2[i]) * E2[i]

print(f'{i} |  V2 = {np.absolute(E2[i]):.5f}  |  O = {np.angle(E2[i],deg=True):.5f}°  |  P2 = {np.real(S2_final):.5f}  |  Q2 = {np.imag(S2_final):.5f}')

while convergencia == False:
    

    E2_new = (1/Y[1,1]) * (np.conj(S2)/np.conj(E2[i]) - Y[1,0]*E1)
    # print(E2_new)
    
    E2.append(E2_new)
    
    i += 1
    
    S2_final = np.conj(Y[1,0]*E1 + Y[1,1]*E2[i]) * E2[i]
    
    print(f'{i} |  V2 = {np.absolute(E2[i]):.5f}  |  O = {np.angle(E2[i],deg=True):.5f}°  |  P2 = {np.real(S2_final):.5f}  |  Q2 = {np.imag(S2_final):.5f}')
    
    if tolerancia > np.absolute(E2[i] - E2[i-1]):
        convergencia = True

0 |  V2 = 1.00000  |  O = 0.00000°  |  P2 = 0.00000  |  Q2 = 0.00000
1 |  V2 = 1.41421  |  O = 8.13010°  |  P2 = 0.60000  |  Q2 = 0.80000
2 |  V2 = 1.27279  |  O = 8.13010°  |  P2 = 0.45000  |  Q2 = 0.45000
3 |  V2 = 1.30431  |  O = 8.82038°  |  P2 = 0.50617  |  Q2 = 0.51852
4 |  V2 = 1.29485  |  O = 8.82038°  |  P2 = 0.49637  |  Q2 = 0.49637
5 |  V2 = 1.29709  |  O = 8.86989°  |  P2 = 0.50043  |  Q2 = 0.50130
6 |  V2 = 1.29642  |  O = 8.86989°  |  P2 = 0.49974  |  Q2 = 0.49974
7 |  V2 = 1.29658  |  O = 8.87340°  |  P2 = 0.50003  |  Q2 = 0.50009
8 |  V2 = 1.29653  |  O = 8.87340°  |  P2 = 0.49998  |  Q2 = 0.49998


### b) 11h (até 12h) - Perda da linha 1

In [25]:
S2 = 0.6 + 0.6j
E2 = [1]

In [26]:
convergencia = False
i = 0
tolerancia = 0.0001

S2_final = np.conj(Y[1,0]*E1 + Y[1,1]*E2[i]) * E2[i]

print(f'{i} |  V2 = {np.absolute(E2[i]):.5f}  |  O = {np.angle(E2[i],deg=True):.5f}°  |  P2 = {np.real(S2_final):.5f}  |  Q2 = {np.imag(S2_final):.5f}')

while convergencia == False:
    

    E2_new = (1/Y[1,1]) * (np.conj(S2)/np.conj(E2[i]) - Y[1,0]*E1)
    # print(E2_new)
    
    E2.append(E2_new)
    
    i += 1
    
    S2_final = np.conj(Y[1,0]*E1 + Y[1,1]*E2[i]) * E2[i]
    
    print(f'{i} |  V2 = {np.absolute(E2[i]):.5f}  |  O = {np.angle(E2[i],deg=True):.5f}°  |  P2 = {np.real(S2_final):.5f}  |  Q2 = {np.imag(S2_final):.5f}')
    
    if tolerancia > np.absolute(E2[i] - E2[i-1]):
        convergencia = True

0 |  V2 = 1.00000  |  O = 0.00000°  |  P2 = 0.00000  |  Q2 = 0.00000
1 |  V2 = 1.49933  |  O = 9.21103°  |  P2 = 0.74400  |  Q2 = 1.03200
2 |  V2 = 1.30725  |  O = 9.21103°  |  P2 = 0.52313  |  Q2 = 0.52313
3 |  V2 = 1.35449  |  O = 10.20601°  |  P2 = 0.61080  |  Q2 = 0.63239
4 |  V2 = 1.33855  |  O = 10.20601°  |  P2 = 0.59294  |  Q2 = 0.59294
5 |  V2 = 1.34277  |  O = 10.29605°  |  P2 = 0.60095  |  Q2 = 0.60284
6 |  V2 = 1.34137  |  O = 10.29605°  |  P2 = 0.59937  |  Q2 = 0.59937
7 |  V2 = 1.34174  |  O = 10.30406°  |  P2 = 0.60008  |  Q2 = 0.60025
8 |  V2 = 1.34162  |  O = 10.30406°  |  P2 = 0.59994  |  Q2 = 0.59994
9 |  V2 = 1.34165  |  O = 10.30478°  |  P2 = 0.60001  |  Q2 = 0.60002


### b) 10h - Perda da linha 2

In [27]:
Z1 = 0.1 + 0.3j
# Z2 = 0.2 + 0.6j

E1 = 1

E2 = [1]
Y = np.zeros((2,2), dtype=np.complex128)

S2 = 0.5 + 0.5j

Zeq = Z1

y12 = 1/Zeq
print(y12)

Y[0,0] = y12
Y[0,1] = -y12
Y[1,0] = -y12
Y[1,1] = y12

(1.0000000000000002-3j)


In [28]:
convergencia = False
i = 0
tolerancia = 0.0001

S2_final = np.conj(Y[1,0]*E1 + Y[1,1]*E2[i]) * E2[i]

print(f'{i} |  V2 = {np.absolute(E2[i]):.5f}  |  O = {np.angle(E2[i],deg=True):.5f}°  |  P2 = {np.real(S2_final):.5f}  |  Q2 = {np.imag(S2_final):.5f}')

while convergencia == False:
    

    E2_new = (1/Y[1,1]) * (np.conj(S2)/np.conj(E2[i]) - Y[1,0]*E1)
    # print(E2_new)
    
    E2.append(E2_new)
    
    i += 1
    
    S2_final = np.conj(Y[1,0]*E1 + Y[1,1]*E2[i]) * E2[i]
    
    print(f'{i} |  V2 = {np.absolute(E2[i]):.5f}  |  O = {np.angle(E2[i],deg=True):.5f}°  |  P2 = {np.real(S2_final):.5f}  |  Q2 = {np.imag(S2_final):.5f}')
    
    if tolerancia > np.absolute(E2[i] - E2[i-1]):
        convergencia = True

0 |  V2 = 1.00000  |  O = 0.00000°  |  P2 = 0.00000  |  Q2 = 0.00000
1 |  V2 = 1.20416  |  O = 4.76364°  |  P2 = 0.55000  |  Q2 = 0.65000
2 |  V2 = 1.16264  |  O = 4.76364°  |  P2 = 0.48276  |  Q2 = 0.48276
3 |  V2 = 1.16857  |  O = 4.90906°  |  P2 = 0.50128  |  Q2 = 0.50383
4 |  V2 = 1.16748  |  O = 4.90906°  |  P2 = 0.49953  |  Q2 = 0.49953
5 |  V2 = 1.16764  |  O = 4.91299°  |  P2 = 0.50003  |  Q2 = 0.50010
6 |  V2 = 1.16761  |  O = 4.91299°  |  P2 = 0.49999  |  Q2 = 0.49999


### b) 11h (até 12h) - Perda da linha 2

In [29]:
S2 = 0.6 + 0.6j
E2 = [1]

In [30]:
convergencia = False
i = 0
tolerancia = 0.0001

S2_final = np.conj(Y[1,0]*E1 + Y[1,1]*E2[i]) * E2[i]

print(f'{i} |  V2 = {np.absolute(E2[i]):.5f}  |  O = {np.angle(E2[i],deg=True):.5f}°  |  P2 = {np.real(S2_final):.5f}  |  Q2 = {np.imag(S2_final):.5f}')

while convergencia == False:
    

    E2_new = (1/Y[1,1]) * (np.conj(S2)/np.conj(E2[i]) - Y[1,0]*E1)
    # print(E2_new)
    
    E2.append(E2_new)
    
    i += 1
    
    S2_final = np.conj(Y[1,0]*E1 + Y[1,1]*E2[i]) * E2[i]
    
    print(f'{i} |  V2 = {np.absolute(E2[i]):.5f}  |  O = {np.angle(E2[i],deg=True):.5f}°  |  P2 = {np.real(S2_final):.5f}  |  Q2 = {np.imag(S2_final):.5f}')
    
    if tolerancia > np.absolute(E2[i] - E2[i-1]):
        convergencia = True

0 |  V2 = 1.00000  |  O = 0.00000°  |  P2 = 0.00000  |  Q2 = 0.00000
1 |  V2 = 1.24579  |  O = 5.52754°  |  P2 = 0.67200  |  Q2 = 0.81600
2 |  V2 = 1.18800  |  O = 5.52754°  |  P2 = 0.57216  |  Q2 = 0.57216
3 |  V2 = 1.19738  |  O = 5.75177°  |  P2 = 0.60237  |  Q2 = 0.60710
4 |  V2 = 1.19540  |  O = 5.75177°  |  P2 = 0.59901  |  Q2 = 0.59901
5 |  V2 = 1.19573  |  O = 5.75971°  |  P2 = 0.60008  |  Q2 = 0.60025
6 |  V2 = 1.19566  |  O = 5.75971°  |  P2 = 0.59997  |  Q2 = 0.59997


As 10h a potência complexa é 0.5 + 0.5j, para a perda na linha 1, a tensão na barra 2 é 16,76% maior do que da barra 1; enquanto que para a perda na linha 2, esse aumento em relação ao modulo da barra 1 é de 29,65%. Com isso, pode-se perceber que com a ausência da linha 2 causa um aumento na corrente e, por consequência, maiores perdas na transmissão. <br><br>
Quando chega às 11h (até 12h) a potência consumida aumenta para 0.6 + 0.6j, o que resulta em um leve aumento da tensão em ambos os casos, aumentando também a corrente solicitada. <br><br> Por fim, a saída da linha 1 provoca um defasamento angular (theta) aproximadamente duas vezes maior do que a saída da linha 2.